# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0002_auto_20171121_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
