# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0003_remove_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRekognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to=b'pictures')),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='ImageRekognition',
        ),
    ]
