# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0004_auto_20180109_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorekognition',
            name='video',
            field=models.FileField(upload_to=b'videos'),
        ),
    ]
