# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekognition', '0005_auto_20180109_0516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageRekognition',
        ),
        migrations.DeleteModel(
            name='VideoRekognition',
        ),
    ]
